sudo: required
services:
  - docker

before_install: 
  - docker build -t dipt912/docker-react -f Dockerfile.dev .
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-807276815737"
  bucket_path: "Docker-React"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"